//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 SafeSoldier.rc 使用
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_SAFESOLDIER_DIALOG          102
#define IDR_MAINFRAME                   128
#define IDD_PE_DIALOG                   130
#define IDD_PRS_DIALOG                  132
#define IDD_SERVER_DIALOG               136
#define IDD_SODR_DIALOG                 138
#define IDD_CLEAR_DIALOG                140
#define IDR_MENU1                       142
#define IDD_TANDM_DIALOG                143
#define IDD_WNDEMU_DIALOG               145
#define IDR_MENU2                       148
#define IDD_SECTION_DIALOG              149
#define IDD_DATADIR_DIALOG              151
#define IDD_EXPORT_DIALOG               153
#define IDD_IMPORT_DIALOG               155
#define IDD_RESOURCE_DIALOG             157
#define IDD_RELOC_DIALOG                159
#define IDD_TLS_DIALOG                  161
#define IDR_MENU3                       165
#define IDR_MENU4                       166
#define IDC_TAB1                        1000
#define IDC_BUTTON1                     1001
#define IDC_SECTION_BUTTON              1001
#define IDC_EXPORT_BUTTON               1001
#define IDC_MD5_BUTTON                  1001
#define IDC_PRS_LIST                    1002
#define IDC_DELFILE_BUTTON              1002
#define IDC_DIRDATA_BUTTON              1002
#define IDC_IMPORT_BUTTON2              1002
#define IDC_PATH_BUTTON                 1002
#define IDC_MODULE_LIST                 1003
#define IDC_RESOURCE_BUTTON             1003
#define IDC_GOOD_BUTTON                 1003
#define IDC_Thread_LIST                 1004
#define IDC_WNDEUM_LIST                 1004
#define IDC_CLEARTRASH_BUTTON           1004
#define IDC_RELOC_BUTTON                1004
#define IDC_CHOICEFILE_BUTTON           1004
#define IDC_DELFILEINFO_LIST            1005
#define IDC_TLS_BUTTON                  1005
#define IDC_Virus_BUTTON                1005
#define IDC_FPANTH_EDIT                 1006
#define IDC_DELAY_BUTTON                1006
#define IDC_FSUF_EDIT                   1007
#define IDC_DELFILEPATH_LIST            1008
#define IDC_GETFILE_BUTTON              1009
#define IDC_ClearMEM_BUTTON             1010
#define IDC_SERVER_LIST                 1011
#define IDC_LFANEW_EDIT                 1012
#define IDC_OEP_EDIT                    1013
#define IDC_SECTION_LIST                1013
#define IDC_NUMOFSECTION_EDIT           1014
#define IDC_EXPORTRVA_EDIT              1014
#define IDC_SIZEOFOP_EDIT               1015
#define IDC_EXPORTSIZE_EDIT             1015
#define IDC_OFFSET_EDIT                 1015
#define IDC_CHARACTER_EDIT              1016
#define IDC_IMPORTRVA_EDIT              1016
#define IDC_TRAIT_EDIT                  1016
#define IDC_IMAGEBASE_EDIT              1017
#define IDC_IMPORTSIZE_EDIT             1017
#define IDC_IMAGEBASE_EDI               1017
#define IDC_SECALIG_EDIT                1018
#define IDC_RESOURCERVA_EDIT            1018
#define IDC_NAMEADD_EDIT                1018
#define IDC_FILEALIG_EDIT               1019
#define IDC_EXCEPTIONRVA_EDIT           1019
#define IDC_NAMESTR_EDIT                1019
#define IDC_SIZEOFIMAGE_EDIT            1020
#define IDC_RESOURCESIZE_EDIT           1020
#define IDC_NUMOFFUN_EDIT               1020
#define IDC_SIZEOFHEADER_EDIT           1021
#define IDC_EXCEPTIONSIZE_EDIT          1021
#define IDC_NUMOFNAMEEDIT               1021
#define IDC_SECURITYRVA_EDIT            1022
#define IDC_EDIT8                       1022
#define IDC_SECURITYSIZE_EDIT           1023
#define IDC_NAEMADDS_EDIT               1023
#define IDC_BASERELOCRVA_EDIT           1024
#define IDC_NAMEINDEXADD_EDIT           1024
#define IDC_BASERELOCSIZE_EDIT          1025
#define IDC_EXPORT_LIST                 1025
#define IDC_DEBUGRVA_EDIT               1026
#define IDC_IMFUNINFO_LIST              1026
#define IDC_DEBUGSIZE_EDIT              1027
#define IDC_IMDLLINFO_LIST              1027
#define IDC_RESOURCE_TREE               1027
#define IDC_ARCHITECTURERVA_EDIT        1028
#define IDC_ROOTNAME_EDIT               1028
#define IDC_ARCHITECTURESIZE_EDIT       1029
#define IDC_ROOTID_EDIT                 1029
#define IDC_CLOBALPTRRVA_EDIT           1030
#define IDC_CHOICENAEM_EDIT             1030
#define IDC_CLOBALPTRSIZE_EDIT          1031
#define IDC_CHOICEID_EDIT               1031
#define IDC_TLSRVA_EDIT                 1032
#define IDC_CHOICERVA_EDIT              1032
#define IDC_TLSSIZE_EDIT                1033
#define IDC_CHOICEOFFSET_EDIT           1033
#define IDC_LOADRVA_EDIT                1034
#define IDC_CHOICESIZE_EDIT             1034
#define IDC_LOADSIZE_EDIT               1035
#define IDC_ROOT_STATIC                 1035
#define IDC_BOUNDRVA_EDIT               1036
#define IDC_CHOICEDIR_STATIC            1036
#define IDC_BOUNDSIZE_EDIT              1037
#define IDC_CHOICE_STATIC               1037
#define IDC_IATRVA_EDIT                 1038
#define IDC_ITEM_LIST                   1038
#define IDC_IATSIZE_EDIT                1039
#define IDC_BLOCK_LIST                  1039
#define IDC_STARTVA_EDIT                1039
#define IDC_DELAURVA_EDIT               1040
#define IDC_ENDVA_EDIT                  1040
#define IDC_DELAYSIZE_EDIT              1041
#define IDC_INDEXVA_EDIT                1041
#define IDC_SODR_LIST                   1041
#define IDC_COMRVA_EDIT                 1042
#define IDC_CALLBACK_EDIT               1042
#define IDC_FILEPATH_EDIT               1042
#define IDC_COMSIZE_EDIT                1043
#define IDC_ZERO_EDIT                   1043
#define IDC_OTHER_BUTTON                1043
#define IDC_OTHERRVA_EDIT               1044
#define IDC_TRAVERSAL_EDIT              1044
#define IDC_OTHERSIZE_EDIT              1045
#define ID_32771                        32771
#define ID_32772                        32772
#define ID_32773                        32773
#define ID_32774                        32774
#define ID_SERVER_32775                 32775
#define ID_SERVER_32776                 32776
#define ID_SERVER_32777                 32777
#define ID_START_SERVER                 32778
#define ID_SUSPENDSERVER                32779
#define ID_STOPSERVER                   32780
#define ID_SERVER_32781                 32781
#define ID_REFRESHSERVER                32782
#define ID_32783                        32783
#define ID_32784                        32784
#define ID_PROTECT                      32785
#define ID_WhiteList                    32787
#define ID_32788                        32788
#define ID_32789                        32789
#define ID_32790                        32790
#define ID_32791                        32791
#define ID_SHUTDOWN                     32792
#define ID_RESTAR                       32793
#define ID_D                            32794
#define ID_DORMANY                      32795
#define ID_32796                        32796
#define ID_Protecte                     32797

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        167
#define _APS_NEXT_COMMAND_VALUE         32798
#define _APS_NEXT_CONTROL_VALUE         1045
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
